name: Publish to npm

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: |
          cd custom-nodes
          npm install

      - name: Build package
        run: |
          cd custom-nodes
          npm run build

      - name: Run tests
        run: |
          cd custom-nodes
          npm test || echo "No tests configured"

      - name: Publish to npm
        run: |
          cd custom-nodes
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
